server:
  origin: [https://www.martinschildrenacademy.com, https://martinschildrenacademy.com]

db:
  url: 'mongodb://rohit:FivoTech%402020@139.59.95.132:27017/mca'
  type: 'mongodb'
  synchronize: true